services:
  - type: web
    name: news
    buildCommand: pip install -r requirements.txt
    startCommand: cd $RENDER_PROJECT_DIR && gunicorn fyp.wsgi:application
    envVars:
      - key: PYTHONPATH
        value: $RENDER_PROJECT_DIR